### ISSUE TITLE
Deprecation notice during fiscal receipt generation

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#296] opened 2022-02-08 21:03 UTC
# Scenario
- connect as an admin
- go to Reçus fiscaux > Année
- generate a fiscal receipt

# Expected behavior
- the messenger does not show any warning

# Current behavior
- for each fiscal receipt, there is a warning `Deprecated: mb_stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated`

**Comment by Yann-BUTSCHER-EIRL** [comment] 2023-04-06 10:11
@LucileDT I can't reproduce the warnings when generating fiscal receipts so we can maybe close this issue for now.
I didn't even found the usage of `mb_stripos` in our code.

**Comment by LucileDT** [comment] 2023-04-06 17:08
@Yann-BUTSCHER-EIRL I wonder if it was a library update which fixed that (as DomPdf had an update fixing a whole lot of things), I'm closing.

**Closed** 2023-04-06 17:08 UTC
Labels: Bug, Scheduled
