### ISSUE TITLE
Make forms navigable by using TAB

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#239] opened 2020-12-14 15:27 UTC
# Context
It seems our forms aren't browsable using the TAB key. 
This behaviour has been observed on chrome browser.

# Todo
- [x] check if work is needed

**Comment by Yann-BUTSCHER-EIRL** [comment] 2021-03-09 13:10
It's working as intended on chromium. Closing for now.

**Closed by Yann-BUTSCHER-EIRL** 2021-03-09 13:10 UTC
Labels: Enhancement
