### ISSUE TITLE
Add a list containing past memberships

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#279] opened 2021-04-24 14:24 UTC
# Context
We currently have access only to a list of active memberships. It would be great to be able to also see past memberships.

# Todo
- [ ] Add a page containing a list of past memberships

**Comment by LucileDT** [comment] 2021-04-24 17:15
Duplicate of #144

**Closed by LucileDT** 2021-04-24 17:15 UTC
Labels: Enhancement
