### ISSUE TITLE
Symfony upgrade broke the revenues chart

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#289] opened 2022-01-30 23:24 UTC
# Scenario
- login
- go to the home page

# Expected behavior
- the revenue chart should be displayed

# Current behavior
- the revenue chart does not load, the API send a 500 error

**Comment by Yann-BUTSCHER-EIRL** [comment] 2022-01-31 11:03
Tested and it works as intended. Closing.

**Closed by Yann-BUTSCHER-EIRL** 2022-01-31 11:03 UTC
Labels: Bug
