### ISSUE TITLE
No text is shown when an image to upload is selected

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#250] opened 2021-01-04 14:31 UTC
# Scenario
- Go to **/association/upload-logo** or **association/upload-treasurer-signature**
- Click browse and select an image to upload

# Expected behavior
When selected, after the selection window closes, the selected file name should appear in the input field

# Current behavior
No text appears, so it feels like it does not work (even though it does)

**Comment by LucileDT** [comment] 2023-06-10 19:40
Duplicate of #204

**Closed by LucileDT** 2023-06-10 19:40 UTC
Labels: Bug
