### ISSUE TITLE
Add way to save the registration of members to the association

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#88] opened 2019-10-21 15:30 UTC
# Context
We need to be able to register subscriptions.

# Todo
- [x] create classes to subscribe
- [ ] create forms to register subscriptions

**Comment by Yann-BUTSCHER-EIRL** [comment] 2020-01-30 10:35
Duplicate of #94 .
Closing.

**Closed by Yann-BUTSCHER-EIRL** 2020-01-30 10:35 UTC
Labels: Duplicate, Enhancement
